mbedtls: Cleanup before reset sources
Problem occurred since I added fail on error (set -e),
when building for different OS in the same tree
(ie: Linux, then Tizen)

Observed error is:

  EXEC_MODE=true ./prep.sh
  scons SECURED=1 WITH_TCP=1 MULTIPLE_OWNER=1 WITH_CLOUD=1 WITH_MQ=SUB,PUB
  ./gbsbuild.sh SECURED=1 WITH_TCP=1 MULTIPLE_OWNER=1 WITH_CLOUD=1 WITH_MQ=SUB,PUB
  error: tests/data_files/server1-bothnames.crt: \
  already exists in working directory

Workaround was to ignore failure errors (like it was in 1.2-rel) using:

  bash ./gbsbuild.sh ...

Bug: https://jira.iotivity.org/browse/IOT-2084
Change-Id: I59fc87f40e41a0095bb6deed042b2a6f7ced0dc1
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/19361
Reviewed-by: Kevin Kane <kkane@microsoft.com>
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Abhishek Sharma <ce.abhishek@samsung.com>
Reviewed-by: Way Vadhanasin <wayvad@microsoft.com>
Reviewed-by: Alex Kelley <alexke@microsoft.com>
Reviewed-by: Uze Choi <uzchoi@samsung.com>