logger: Fix missing include for size_t
Observed issue on Tizen:Common:

  resource/csdk/logger/include/trace.h:60:65:\
   error: unknown type name 'size_t'
  resource/csdk/logger/src/trace.c:29:65:\
   error: unknown type name 'size_t'

Change-Id: Ic4c4a492d238b4f9d7860720fa10c92dfca051f8
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/17963
Reviewed-by: Mats Wichmann <mats@linux.com>
Reviewed-by: Ziran Sun <ziran.sun@samsung.com>