Don't include cacommon.h in sample apps
cacommon.h is not a Public header.

This also fixes recent Windows build breaks:

ocserver.cpp
C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(100):
error C2220: warning treated as error - no 'object' file generated

C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(100):
warning C4005: 'AF_IPX': macro redefinition

C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock.h(452):
note: see previous definition of 'AF_IPX'

C:\Program Files (x86)\Windows Kits\8.1\include\shared\ws2def.h(140):
warning C4005: 'AF_MAX': macro redefinition
...

Change-Id: I4c6ac41a5869c2dced1f38a8eed09c4ab42e2076
Signed-off-by: Dan Mihai <Daniel.Mihai@microsoft.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/20057
Reviewed-by: Ibrahim Esmat <iesmat@microsoft.com>
Tested-by: jenkins-iotivity <jenkins@iotivity.org>