fix notification manager sample app build error
liboc.so isn't required to be linked when build C application
Otherwise there may be following error:

out/linux/x86_64/release/liboc.so: undefined reference to
`std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long)
const@GLIBCXX_3.4.18'

Change-Id: Idbb5ca305c22477aba19495c8e2b8cf5278bd058
Signed-off-by: Caiwen Zhang<caiwen.zhang@intel.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/554
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: minsuk1.choi <minsuk1.choi@samsung.com>
Reviewed-by: JungYong KIM <jyong2.kim@samsung.com>
Reviewed-by: Heewon Parkhi <h_w.park@samsung.com>
Reviewed-by: Uze Choi <uzchoi@samsung.com>