tizen: Disable Bluetooth for Tizen:IVI (capi outdated)
Make sure capi-network-bluetooth-devel
 is shipping bluetooth_internal.h.

For instance, 0.1.39 does not have it, while 0.1.52 have it.

In that case it will fail to build and report a message like:

   resource/csdk/connectivity/src/bt_edr_adapter/tizen/\
   caedrclient.c:30:32: \
   fatal error: bluetooth_internal.h: No such file or directory

This need to be checked for other Tizen profiles:
 Tizen:2.3.1:Wearable, Tizen:2.4:Mobile have it.

Bug: https://jira.iotivity.org/browse/IOT-1343
Change-Id: I028f3c4fd8c9526b5d06a55b0f2a5f5c6c113d3d
Origin: https://gerrit.iotivity.org/gerrit/#/c/12355/
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/12355
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Ziran Sun <ziran.sun@samsung.com>
(cherry picked from commit 61382c1df95115ef595b06e023d59bcca8bad22c)
Reviewed-on: https://gerrit.iotivity.org/gerrit/13509