Fix a build problem on recent linux host
Provisioning unittest will not link when pointed at
connectivity_abstraction_insternal due to dependency of other libs on
connectivity_abstraction.  Leads to this error:

/bin/ld: out/linux/x86_64/debug/libroutingmanager.a(routingmanager.o): undefined reference to symbol 'u_linklist_length'
/home/mats/iotivity.work/out/linux/x86_64/debug//libconnectivity_abstraction.so: error adding symbols: DSO missing from command line

It works fine to link against connectivity_abstraction so use that instead.

Other changes in the SConscript are just cleanup.

Change-Id: I47b846111f4bbaee0ce4d38de7d9e8a0ccc3885b
Bug: https://jira.iotivity.org/browse/IOT-2864
Signed-off-by: Mats Wichmann <mats@linux.com>