webOS: Fix missing return statement
:Release Notes:
Fix missing return statement

:Detailed Notes:
This commit fixes build error regarding missing return statement
of oc{server, client}basicops.

resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops.cpp:578:1:
error: control reaches end of non-void function [-Werror=return-type]
resource/csdk/stack/samples/webos/secure/occlientbasicops/occlientbasicops.cpp:585:1:
error: no return statement in function returning non-void [-Werror=return-type]
resource/csdk/stack/samples/webos/secure/ocserverbasicops/ocserverbasicops.cpp:591:1:
error: no return statement in function returning non-void [-Werror=return-type]

:Testing Performed:
Verified that oc{server,client}basicops works as expected.

:Issues Addressed:
[IOT-3302] webOS: Fix build error regarding missing return statement

Signed-off-by: sungmok.shin <sungmok.shin@lge.com>
Change-Id: I310983b17840a3c85e3cf43f8cc635e411ada37f
Signed-off-by: sungmok.shin <sungmok.shin@lge.com>