VS2013/15 aggregate changes of Intel and Microsoft
Status: Compiles in VS2015 and runs tests

List of TODOs:

  TODO: Fix tinydtls tick and locking issues.
  TODO: Fix disabled tests (PersistentStorageHandlerTest, usleep)
  TODO: Enable ocpmapi.dll shared lib (currently it's static)
  TODO: Remove hacks to solve error C2059: syntax error: 'constant'
          see: resource\include\StringConstants.h
  TODO: Address inconsistent style! Perhaps file a JIRA issue; CI
        should reject such issues before they enter the code base.
  TODO: Understand priority around enabling services.

Merger changelog:

* Adopted libtimer\timer.c changes from Microsoft
* Adopted Boost SCons installation changes from Intel
* Combined build_common\windows\SConscript from both Intel and
  Microsoft
* Adopted tinydtls code changes from Microsoft (INLINE_API macro,
  features wrapped in #ifdefs, etc)
* Adopted tinydtls SCons changes from Intel, tinydtls random seed
  generation from Intel
* Adopted ocrandom.c "QueryPerformanceCounter" from Microsoft.
* Adopted resource\examples from Intel
* Adopted liboc_logger and liboc from Intel
* Adopted resource/src from Intel
* Adopted boostification from Microsoft (BOOST_NOEXCEPT, etc.)
* Adopted "getopt" from Microsoft (multiple locations)
  - resource\csdk\stack\samples\linux\secure\occlientbasicops.cpp
  - resource\csdk\stack\samples\linux\SimpleClientServer\common.cpp
* Adopted SimpleClientServer changes from Microsoft
  - resource\csdk\stack\samples\linux\SimpleClientServer\
* Adopted oicgroup.c from Intel
* Adopted OC_EXPORT changes (and OC_EXPORT_DLL define macro)
  from Microsoft

Change-Id: Ib4298cd63731b39e1bcfa6a790fd18298c73720a
Signed-off-by: Henry Beberman <henry.beberman@intel.com>
Signed-off-by: Dave Thaler <dthaler@microsoft.com>
Signed-off-by: Daniel Ferguson <daniel.j.ferguson@intel.com>
Signed-off-by: David Antler <david.a.antler@intel.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/7627
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>