connectivity: Link unitest to mbedcrypto
Problem was observed while building with SECURED=0 and gcc-6.3

g++ \
-o out/linux/x86_64/release/resource/csdk/connectivity/test/catests \
(...)
/bin/ld: \
out/linux/x86_64/release/libc_common.a(oic_platform.o): \
undefined reference to symbol 'mbedtls_md_info_from_type'
liboctbstack.so: error adding symbols: DSO missing from command line

Change-Id: I46fc1f4cb7597b3396cb1bc29889db5ba9828d57
Signed-off-by: Todd Malsbary <todd.malsbary@intel.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/19377
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Dan Mihai <Daniel.Mihai@microsoft.com>