Build: add gtest libs automatically
Once gtest's sconfile is imported, build flags are propagated.

This change is part of a massive cleanup change:

  https://gerrit.iotivity.org/gerrit/#/c/249/

Problem was observed with g++-4.8.4 (Ubuntu 14.04.4)
 which needs pthread to be after gtest on cmdline :

  g++ -o out/linux/x86_64/debug/service/resource-encapsulation/src/resourceBroker/unittest/broker_test  \
  (...) \
  -L. -lcoap -lc_common -llogger -ldl -lpthread -lrt -luuid -lroutingmanager -lboost_thread -lboost_system -lconnectivity_abstraction -loc_logger -loctbstack -loc -lrcs_client -lrcs_common -lgtest -lgtest_main

  /usr/bin/ld: extlibs/gtest/gtest-1.7.0/lib/.libs/libgtest.a(gtest-all.o): \
    undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
  /lib/x86_64-linux-gnu/libpthread.so.0: \
    error adding symbols: DSO missing from command line

Bug: https://jira.iotivity.org/browse/IOT-863
Bug-AGL: https://jira.automotivelinux.org/browse/SPEC-158
Change-Id: I7a0b0e1c9c1760fd29694fafec5befa1d4245eb1
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/9447
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Ziran Sun <ziran.sun@samsung.com>
Reviewed-by: Jon A. Cruz <jon@joncruz.org>