build: Stop logging RD if not wanted
 - Also polish use of LOGGING / TB_LOG option.
 - When using scons CPPDEFINES there is no need to add -D prefix.
 - Add machine readable header in python files (to avoid tabs).

Without this change,
 even if LOGGING is unset, extra verbose log is printed :

  DEBUG: SRM: SRMRegisterHandler !!
  DEBUG: SRM-PSI: GetSecureVirtualDatabaseFromPS IN
  ERROR: SRM-PSI: ps is NULL
  DEBUG: SRM-DOXM: ReadSVDataFromPS failed

This does not occurs in master branch.

Change-Id: Ibfae4ee23b6b157e891e9792c464cd9a00000001
Bug: https://jira.iotivity.org/browse/IOT-1203
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/9847
Reviewed-by: Gabriel Schulhof <gabriel.schulhof@intel.com>
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Ziran Sun <ziran.sun@samsung.com>