provisioning: Fix type mismatch for sessionObject.expiresin
Failure to build was observed on Tizen:Common (armv7l):

  cloudAuth.cpp:127:59: error: cannot convert 'long int*' to 'int64_t* \
  {aka long long int*}' for argument '3' to \
  'bool OCRepPayloadGetPropInt(const OCRepPayload*, const char*, int64_t*)'

Change-Id: I3feaea196d91e22d29cc0a2b1d5fc859ecb6ea6c
Origin: https://gerrit.iotivity.org/gerrit/#/c/12049/
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/12049
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Habib Virji <habib.virji@samsung.com>
(cherry picked from commit cdca139c2403d88e3cb92af30f4cfe15b5e6b9fa)
Reviewed-on: https://gerrit.iotivity.org/gerrit/12143
Reviewed-by: Ashwini  Kumar <k.ashwini@samsung.com>
Reviewed-by: Dave Thaler <dthaler@microsoft.com>
Reviewed-by: Ziran Sun <ziran.sun@samsung.com>