connectivity: Link unitest to ocsrm
Problem was observed while building with clang on GNU/Linux or gcc-6.3

  clang++-3.5 \
  -o out/linux/x86_64/release/resource/csdk/connectivity/test/catests \
  (...)
  /usr/bin/ld: \
  out/linux/x86_64/release/liboctbstack_internal.a(ocpayloadparse.o): \
  undefined reference to symbol 'cbor_value_leave_container'
  liboctbstack.so: error adding symbols: DSO missing from command line

Bug: https://jira.iotivity.org/browse/IOT-1745
Change-Id: Icf8196858f46e5458e70b3e3bd6239ff0d4c688b
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Change-Id: I13aceaa9817b77991a316888efe7cf761bcd2266
Reviewed-on: https://gerrit.iotivity.org/gerrit/19303
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Dan Mihai <Daniel.Mihai@microsoft.com>