build: Reformat resource/csdk to be more Pythonic
[Mats Wichmann]

Reformat resource/csdk SConscripts to be more Pythonic 2/4

These are the resource/csdk/stack subset

There are not intended to be any functional changes, with a minor
exception: in resource/csdk/stack/samples/linux/secure/SConscript,
the samples are now assigned to an appropriately constructed list,
which is assigned an Alias, rather than two similar but different
conditional Alias lines with the list inline.

There is no consistently "pretty" way to fold long lines,
the choices were made by a tool (yapf) but occasionally
overridden to be a little more consistent

The test harness is now consistently imported as:
  from tools.scons.RunTest import run_test
rather than import * - should normally avoid importing whole
namespace unqualified unless it is really needed

[Philippe Coval]

Merge from master to 1.3-rel

Conflicts:
	resource/csdk/stack/samples/arduino/SimpleClientServer/ocserver/SConscript
	resource/csdk/stack/samples/tizen/build/SConscript
	resource/csdk/stack/samples/tizen/build/scons/SConscript
	resource/csdk/stack/test/SConscript

Change-Id: I0e15b375a052ef792b2a1c4470552e5e0e4fb3fc
Signed-off-by: Mats Wichmann <mats@linux.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/20697
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Phil Coval <philippe.coval@osg.samsung.com>
Origin: master
Bug: https://jira.iotivity.org/browse/IOT-1745
Signed-off-by: Phil Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/20909
Reviewed-by: Dan Mihai <Daniel.Mihai@microsoft.com>
Reviewed-by: George Nash <george.nash@intel.com>