build: Suggest to download tinycbor v0.2.1
Related to error about undefined reference to _cbor_value_dup
 introduced by new files.

Note this patch is appropriate for frozen versions
 while master or development branches can follow tinycbor master
 and eventually synched when needed.

Change-Id: Ic764a3aa7231982d24fcdd17d66142557bfd8d8a
Cc: Thiago Macieira <thiago.macieira@intel.com>
Credit-to: kartik6402 <karthikeyan.selvaraj@intel.com>
Origin: https://gerrit.iotivity.org/gerrit/#/c/9449
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/9565
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Ashwini  Kumar <k.ashwini@samsung.com>
Reviewed-by: Habib Virji <habib.virji@samsung.com>
Reviewed-by: Uze Choi <uzchoi@samsung.com>