plugins: Use common params for Werror flag
This flag should be used at project level using build_common settings

For reference the build issue was oberved on Yocto's poky master:

    bridging/plugins/lifx_plugin/lifx_objects/lifx.cpp:83:53:\
    required from here
    extlibs/rapidjson/rapidjson/include/rapidjson/document.h:1635:24: \
    error: 'void* memcpy(void*, const void*, size_t)' \
    writing to an object of type \
    'class rapidjson::GenericValue<rapidjson::UTF8<> >' \
    with no trivial copy-assignment; \
    use copy-assignment or copy-initialization instead \
    [-Werror=class-memaccess]
    std::memcpy(data_.a.elements, values, count * sizeof(GenericValue));
    (...)

Change-Id: I4b820e50158e34a94d84195e4979ada6fefff190
Signed-off-by: Philippe Coval <p.coval@samsung.com>