android: add misssing error codes to stackResultToStr()
The OC_STACK_UNAUTHORIZED_REQ error code and some others were missing in
the method for translating them into strings.
Without this patch it resulted in this exception:
org.iotivity.base.OcException: stack error in onObserveCallback JNI_INVALID_VALUE

Change-Id: I739dfecafff55c035702a27a9b5d8dcb925993f4
Signed-off-by: Hauke Mehrtens <hauke.mehrtens@lantiq.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/2643
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Tim Kourt <tim.a.kourt@intel.com>
Reviewed-by: Patrick Lankswert <patrick.lankswert@intel.com>
(cherry picked from commit c8487deda0f5ee888267c53322c6197a463c1b88)
Reviewed-on: https://gerrit.iotivity.org/gerrit/2989
Reviewed-by: Madan Lanka <lanka.madan@samsung.com>