Fix compile error with g++ 6.3.1 and RD unit tests.
gtest.h: In instantiation of 'testing::AssertionResult \
    testing::internal::CmpHelperNE(const char*, const char*, const \
    T1&, const T2&) [with T1 = long int; T2 = char*]':
rddatabase.cpp:126:9:   required from here
gtest.h:1577:28: error: ISO C++ forbids comparison between pointer \
    and integer [-fpermissive]

Change-Id: I6e5a2863fc6d45dffb5bc61526ae9f786eb1c638
Signed-off-by: Todd Malsbary <todd.malsbary@intel.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/20263
Reviewed-by: Phil Coval <philippe.coval@osg.samsung.com>
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Uze Choi <uzchoi@samsung.com>