Fix the notification service SConscript
 - when application use the notification service, build error occurs.
 - i.e) /usr/include/service/notification/NSConsumerInterface.h:35:22: fatal error: NSCommon.h: No such file or directory
 - Although NSConsumerInterface.h includes NSCommon.h, NSCommon.h file is not installed in SConscript.
 - So, need to add NSCommon.h in installed header

Change-Id: I2f28f84504d68c5506c89513d74adcdf32d2bbfc
Signed-off-by: JooseokPark <jooseok.park@samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/16427
Reviewed-by: Phil Coval <philippe.coval@osg.samsung.com>
Tested-by: jenkins-iotivity <jenkins-iotivity@opendaylight.org>
Reviewed-by: Uze Choi <uzchoi@samsung.com>
(cherry picked from commit e4eca38246a40013530b7df74c1b369960c88897)
Reviewed-on: https://gerrit.iotivity.org/gerrit/16459
Tested-by: Uze Choi <uzchoi@samsung.com>