bridging: Return false boolean instead of enum
Small Fix to support g++-7.1.0

It was tested on yocto poky master on iotivity-1.3.0 (and later):

  bridging/plugins/nest_plugin/nest_objects/nest.cpp: \
  In member function 'bool Nest::isAuthorized()':
  bridging/plugins/nest_plugin/nest_objects/nest.cpp:95:16: \
  error: enum constant in boolean context [-Werror=int-in-bool-context]

Change-Id: Ib53aa7be0198cd926b6901b173001910a324633e
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/21071
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Dan Mihai <Daniel.Mihai@microsoft.com>
Reviewed-by: Todd Malsbary <todd.malsbary@intel.com>