Fix two "implicit function declarations
service/easy-setup/enrollee/src/easysetup.c:182:9: warning: implicit declaration of function 'RegisterConnectRequestEventCallBack' [-Wimplicit-function-declaration]
service/notification/examples/linux/notificationprovider.c:99:14: warning: implicit declaration of function 'strcmp' [-Wimplicit-function-declaration]

Change-Id: I0e449b2834da90422f44e116c6ee91f241d6ec9e
Signed-off-by: Mats Wichmann <mats@linux.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/18613
Reviewed-by: Phil Coval <philippe.coval@osg.samsung.com>
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
Reviewed-by: Dave Thaler <dthaler@microsoft.com>
Reviewed-by: Jihun Ha <jihun.ha@samsung.com>
Reviewed-by: Uze Choi <uzchoi@samsung.com>
(cherry picked from commit f33bfc11627ee1adc9bcde85fea4e5f1df0ca197)
Reviewed-on: https://gerrit.iotivity.org/gerrit/19943